name: Sync

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  public-to-internal:
    if: ${{ github.repository == 'perpetual-protocol/perp-curie-contract' }}
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.PERP_LUSHAN_DEPLOY_PRIVATE_KEY }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git config --global user.name "dev"
          git config --global user.email "dev@perp.com"
          git remote add internal "git@github.com:perpetual-protocol/perp-lushan.git"
          git push --set-upstream internal main
